server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Injection de l'URL du backend
    location / {
        try_files $uri $uri/ /index.html;
        sub_filter_once off;
        sub_filter 'window.API_URL = window.API_URL || "http://localhost:3000"' 'window.API_URL = window.API_URL || "http://backend:3000"';
    }
}