apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_DATABASE: contacts_db
  MYSQL_USER: contact_user
  MYSQL_PASSWORD: contact_password
  MYSQL_ROOT_PASSWORD: root_password